kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
apiVersion: v1
data:
  filebeat.yml: |+

    filebeat.prospectors:
    - type: log
      enabled: true
      paths:
        - /var/log/containers/*.log
      # Required in minikube, probably not an issue elsewhere
      # https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#_symlinks
      symlinks: true

    processors:
    - add_kubernetes_metadata:
        in_cluster: true

    output.kafka:
      hosts: ["kafka-0.broker.kafka.svc.cluster.local:9092", "kafka-1.broker.kafka.svc.cluster.local:9092", "kafka-2.broker.kafka.svc.cluster.local:9092"]
      topic: ops-kube-logs-raw-001
      
      partition.round_robin:
        reachable_only: false

      client_id: filebeat-kubernetes
      version: 0.11.0.0
      required_acks: 1
      compression: gzip
      max_message_bytes: 1000000