apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logs-kafka
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: logs-kafka
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: filebeat
        image: solsson/kafka-filebeat-kubernetes
        imagePullPolicy: Never
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers