apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logs-kafka
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: logs-kafka
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: filebeat
        image: solsson/kafka-filebeat-kubernetes@sha256:79b40d81b892ffb3b917eb249f4b3050badf57fadffbdc35272060c9b377209e
        command:
        - filebeat
        - -e
        - -c
        - /etc/filebeat/filebeat.yml
        #- -d
        #- "*"
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat
          readOnly: true
        - name: data
          mountPath: /data
        - name: varlog
          mountPath: /var/log
          readOnly: true
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: filebeat-config
      - name: data
        hostPath:
          path: /kubernets-filebeat-state
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers