apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: logs-kafka
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: logs-kafka
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      containers:
      - name: kafkacat
        image: solsson/kafkacat@sha256:36d1f191cc33a8365074280279205e6b4f52cd8cc8fb1b896bb4c943c9dee8f8
        command:
        - sh
        - -ec
        - 'tail -f /dev/null'
        resources:
          limits:
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 100Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      terminationGracePeriodSeconds: 10
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
